Handle no -o

diff --git a/compile-r7rs b/compile-r7rs
--- a/compile-r7rs
+++ b/compile-r7rs
@@ -43,8 +43,16 @@ prepend_dirs="${prepend_dirs#:}"
 append_dirs="${append_dirs#:}"
 prepend_dirs="${prepend_dirs#,}"
 append_dirs="${append_dirs#,}"
-prefix="#!/usr/bin/env -S"
 
+if [ "${input_file:-}" = "" ]; then echo "Error, no input file"; exit 1; fi
+
+case ${input_file:-} in
+    *.sps) output_file="${input_file%.sps}";;
+    *.scm) output_file="${input_file%.scm}";;
+    *) echo "Error, invalid input file";;
+esac
+
+prefix="#!/usr/bin/env -S"
 case $rnrs in
     r6rs)
         case $COMPILE_R7RS in
